import React, { useState, useRef } from 'react';
import './Dashboard.css';

const API_BASE = import.meta.env.VITE_API_BASE || '';

const npkOptions = ['Low', 'Medium', 'High'];
const growthStages = ['Seedling', 'Vegetative', 'Flowering', 'Fruiting', 'Maturity'];
const soilTypes = ['Sandy', 'Clay', 'Loamy', 'Silty', 'Peaty', 'Chalky'];

const initialForm = {
  cropName: '', location: '', soilType: '', soilPh: '',
  nitrogenLevel: 'Medium', phosphorusLevel: 'Medium', potassiumLevel: 'Medium',
  moisture: '', temperature: '', humidity: '', rainfall: '',
  growthStage: '', organicFarming: false, budget: '', problemDescription: ''
};

const Dashboard = () => {
  const [formData, setFormData] = useState(initialForm);
  const [loading, setLoading] = useState(false);
  const [recommendation, setRecommendation] = useState(null);
  const [error, setError] = useState(null);
  const [activeTab, setActiveTab] = useState('form');
  const reportRef = useRef(null);
  const [chatMessages, setChatMessages] = useState([]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const sessionId = useRef(`session_${Date.now()}`);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setRecommendation(null);

    // Build payload matching backend FarmerQuery model
    const payload = {
      cropName: formData.cropName,
      location: formData.location,
      soilType: formData.soilType,
      soilPh: formData.soilPh ? parseFloat(formData.soilPh) : null,
      nitrogenLevel: formData.nitrogenLevel,
      phosphorusLevel: formData.phosphorusLevel,
      potassiumLevel: formData.potassiumLevel,
      moisture: formData.moisture ? parseFloat(formData.moisture) : null,
      temperature: formData.temperature ? parseFloat(formData.temperature) : null,
      humidity: formData.humidity ? parseFloat(formData.humidity) : null,
      rainfall: formData.rainfall ? parseFloat(formData.rainfall) : null,
      growthStage: formData.growthStage,
      organicFarming: formData.organicFarming,
      budget: formData.budget,
      problemDescription: formData.problemDescription,
    };

    console.log('[AgriAgent] Submitting to /api/recommend:', JSON.stringify(payload));

    try {
      const res = await fetch(`${API_BASE}/api/recommend`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      console.log('[AgriAgent] Response status:', res.status);

      if (!res.ok) {
        const errText = await res.text();
        console.error('[AgriAgent] Server error body:', errText);
        throw new Error(`Server responded with status ${res.status}: ${errText}`);
      }

      const data = await res.json();
      console.log('[AgriAgent] Recommendation received:', data.recommendedFertilizer);
      setRecommendation(data);
      setActiveTab('report');
    } catch (err) {
      console.error('[AgriAgent] API error:', err);
      setError('❌ ' + (err.message || 'Failed to connect to the backend. Please ensure the server is running on port 8080.'));
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setFormData(initialForm);
    setRecommendation(null);
    setError(null);
    setActiveTab('form');
    setChatMessages([]);
    sessionId.current = `session_${Date.now()}`;
  };

  const handleChatSubmit = async (e) => {
    e.preventDefault();
    if (!chatInput.trim()) return;

    const userMsg = chatInput;
    setChatInput('');
    setChatMessages(prev => [...prev, { role: 'user', content: userMsg }]);
    setChatLoading(true);

    try {
      const res = await fetch(`${API_BASE}/api/chat/message`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sessionId: sessionId.current, message: userMsg }),
      });
      const data = await res.json();
      setChatMessages(prev => [...prev, { role: 'agent', content: data.content }]);
    } catch (err) {
      console.error('Chat error:', err);
      setChatMessages(prev => [...prev, { role: 'agent', content: 'Sorry, failed to connect to chat agent.' }]);
    } finally {
      setChatLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!recommendation) return;
    const content = `
FERTILIZER RECOMMENDATION REPORT
Generated by AgriAgent AI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CROP DETAILS
Crop Name    : ${formData.cropName}
Location     : ${formData.location}
Growth Stage : ${formData.growthStage}
Soil pH      : ${formData.soilPh}
Soil Type    : ${formData.soilType}
NPK Levels   : N-${formData.nitrogenLevel} | P-${formData.phosphorusLevel} | K-${formData.potassiumLevel}
Organic Farm : ${formData.organicFarming ? 'Yes' : 'No'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AI RECOMMENDATION
Recommended Fertilizer : ${recommendation.recommendedFertilizer || 'N/A'}
Quantity               : ${recommendation.quantity || 'N/A'}
Application Method     : ${recommendation.applicationMethod || 'N/A'}
Timing                 : ${recommendation.timing || 'N/A'}

REASON
${recommendation.reason || 'N/A'}

IRRIGATION ADVICE
${recommendation.irrigationAdvice || 'N/A'}

PRECAUTIONS
${recommendation.precautions || 'N/A'}

ORGANIC ALTERNATIVES
${recommendation.organicAlternatives || 'N/A'}

EXPECTED IMPROVEMENT
${recommendation.expectedImprovement || 'N/A'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated on: ${new Date().toLocaleString()}
AgriAgent · AI-Powered Fertilizer Recommendation System
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AgriAgent_Report_${formData.cropName}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const ReportCard = ({ icon, label, value, highlight }) => (
    <div className={`report-card ${highlight ? 'report-card-highlight' : ''}`}>
      <div className="report-card-icon">{icon}</div>
      <div className="report-card-content">
        <span className="report-card-label">{label}</span>
        <span className={`report-card-value ${highlight ? 'value-highlight' : ''}`}>{value || '—'}</span>
      </div>
    </div>
  );

  return (
    <div className="dashboard-wrapper animate-fade-in">

      {/* Header */}
      <div className="dashboard-header">
        <div className="dashboard-title-block">
          <h1 className="dashboard-title">Fertilizer Recommendation</h1>
          <p className="dashboard-subtitle">Enter your farm details to receive an AI-generated fertilizer plan</p>
        </div>
        <div className="dashboard-tabs">
          <button
            className={`tab-btn ${activeTab === 'form' ? 'tab-active' : ''}`}
            onClick={() => setActiveTab('form')}
          >
            📝 Input Form
          </button>
          <button
            className={`tab-btn ${activeTab === 'report' ? 'tab-active' : ''}`}
            onClick={() => recommendation && setActiveTab('report')}
            disabled={!recommendation}
          >
            📊 AI Report
          </button>
        </div>
      </div>

      {/* ---- FORM TAB ---- */}
      {activeTab === 'form' && (
        <div className="form-container glass-card">
          <form onSubmit={handleSubmit} className="farmer-form">

            {/* Section 1: Crop & Location */}
            <div className="form-section-group">
              <div className="form-section-label">
                <span className="form-section-icon">🌾</span>
                Crop & Location
              </div>
              <div className="form-grid">
                <div className="form-field">
                  <label>Crop Name <span className="required">*</span></label>
                  <input
                    type="text" name="cropName" value={formData.cropName}
                    onChange={handleChange} required placeholder="e.g. Tomato, Rice, Wheat"
                  />
                </div>
                <div className="form-field">
                  <label>Location <span className="required">*</span></label>
                  <input
                    type="text" name="location" value={formData.location}
                    onChange={handleChange} required placeholder="City or Region"
                  />
                </div>
                <div className="form-field">
                  <label>Soil Type</label>
                  <select name="soilType" value={formData.soilType} onChange={handleChange}>
                    <option value="">Select Soil Type</option>
                    {soilTypes.map(s => <option key={s} value={s}>{s}</option>)}
                  </select>
                </div>
                <div className="form-field">
                  <label>Growth Stage <span className="required">*</span></label>
                  <select name="growthStage" value={formData.growthStage} onChange={handleChange} required>
                    <option value="">Select Stage</option>
                    {growthStages.map(s => <option key={s} value={s}>{s}</option>)}
                  </select>
                </div>
              </div>
            </div>

            {/* Section 2: Soil Nutrients */}
            <div className="form-section-group">
              <div className="form-section-label">
                <span className="form-section-icon">🧪</span>
                Soil Nutrients
              </div>
              <div className="form-grid">
                <div className="form-field">
                  <label>Soil pH <span className="required">*</span></label>
                  <input
                    type="number" step="0.1" min="0" max="14" name="soilPh"
                    value={formData.soilPh} onChange={handleChange} required placeholder="e.g. 6.5"
                  />
                </div>
                <div className="form-field">
                  <label>Nitrogen (N)</label>
                  <div className="npk-selector">
                    {npkOptions.map(opt => (
                      <button
                        key={opt} type="button"
                        className={`npk-btn npk-${opt.toLowerCase()} ${formData.nitrogenLevel === opt ? 'npk-active' : ''}`}
                        onClick={() => setFormData(p => ({ ...p, nitrogenLevel: opt }))}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="form-field">
                  <label>Phosphorus (P)</label>
                  <div className="npk-selector">
                    {npkOptions.map(opt => (
                      <button
                        key={opt} type="button"
                        className={`npk-btn npk-${opt.toLowerCase()} ${formData.phosphorusLevel === opt ? 'npk-active' : ''}`}
                        onClick={() => setFormData(p => ({ ...p, phosphorusLevel: opt }))}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="form-field">
                  <label>Potassium (K)</label>
                  <div className="npk-selector">
                    {npkOptions.map(opt => (
                      <button
                        key={opt} type="button"
                        className={`npk-btn npk-${opt.toLowerCase()} ${formData.potassiumLevel === opt ? 'npk-active' : ''}`}
                        onClick={() => setFormData(p => ({ ...p, potassiumLevel: opt }))}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Section 3: Weather */}
            <div className="form-section-group">
              <div className="form-section-label">
                <span className="form-section-icon">🌤️</span>
                Weather Conditions (Optional)
              </div>
              <div className="form-grid">
                <div className="form-field">
                  <label>Moisture (%)</label>
                  <input type="number" step="0.1" name="moisture" value={formData.moisture} onChange={handleChange} placeholder="e.g. 45" />
                </div>
                <div className="form-field">
                  <label>Temperature (°C)</label>
                  <input type="number" step="0.1" name="temperature" value={formData.temperature} onChange={handleChange} placeholder="e.g. 28" />
                </div>
                <div className="form-field">
                  <label>Humidity (%)</label>
                  <input type="number" step="0.1" name="humidity" value={formData.humidity} onChange={handleChange} placeholder="e.g. 70" />
                </div>
                <div className="form-field">
                  <label>Rainfall (mm)</label>
                  <input type="number" step="0.1" name="rainfall" value={formData.rainfall} onChange={handleChange} placeholder="e.g. 120" />
                </div>
              </div>
            </div>

            {/* Section 4: Additional */}
            <div className="form-section-group">
              <div className="form-section-label">
                <span className="form-section-icon">📋</span>
                Additional Details
              </div>
              <div className="form-grid">
                <div className="form-field">
                  <label>Budget (₹/acre)</label>
                  <input type="text" name="budget" value={formData.budget} onChange={handleChange} placeholder="e.g. 5000" />
                </div>
                <div className="form-field organic-toggle-field">
                  <label>Farming Preference</label>
                  <div className="toggle-wrap">
                    <div
                      className={`organic-toggle ${formData.organicFarming ? 'toggle-on' : ''}`}
                      onClick={() => setFormData(p => ({ ...p, organicFarming: !p.organicFarming }))}
                      role="switch"
                      aria-checked={formData.organicFarming}
                    >
                      <div className="toggle-thumb" />
                    </div>
                    <span className="toggle-label">
                      {formData.organicFarming ? '🌿 Organic Farming' : '⚗️ Conventional Farming'}
                    </span>
                  </div>
                </div>
                <div className="form-field full-width">
                  <label>Problem Description</label>
                  <textarea
                    name="problemDescription" value={formData.problemDescription}
                    onChange={handleChange} rows="3"
                    placeholder="Describe any issues: e.g. Yellowing leaves, stunted growth, pest attack..."
                  />
                </div>
              </div>
            </div>

            {/* Error */}
            {error && (
              <div className="error-box">
                <span className="error-icon">⚠️</span>
                <div>
                  <strong>Connection Error</strong>
                  <p>{error}</p>
                </div>
              </div>
            )}

            {/* Submit */}
            <div className="form-actions">
              <button type="button" className="btn-secondary" onClick={handleReset}>
                Reset Form
              </button>
              <button type="submit" className="btn-primary submit-btn" disabled={loading}>
                {loading ? (
                  <>
                    <span className="spinner" />
                    Analyzing with AI...
                  </>
                ) : (
                  '🌱 Get AI Recommendation'
                )}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* ---- REPORT TAB ---- */}
      {activeTab === 'report' && recommendation && (
        <div className="report-wrapper animate-fade-in" ref={reportRef}>

          {/* Report Header */}
          <div className="report-header glass-card">
            <div className="report-hero-icon">🌱</div>
            <div className="report-hero-text">
              <span className="badge badge-success">✓ AI Report Generated</span>
              <h2 className="report-hero-title">{recommendation.recommendedFertilizer}</h2>
              <p className="report-hero-sub">
                For <strong>{formData.cropName}</strong> in <strong>{formData.growthStage}</strong> stage · {formData.location}
              </p>
            </div>
            <div className="report-actions">
              <button className="btn-secondary" onClick={() => setActiveTab('form')}>
                ← Edit Input
              </button>
              <button className="btn-primary" onClick={handleDownloadPDF}>
                ⬇ Download Report
              </button>
            </div>
          </div>

          {/* Key Metrics */}
          <div className="report-metrics">
            <ReportCard icon="🌿" label="Fertilizer" value={recommendation.recommendedFertilizer} highlight />
            <ReportCard icon="⚖️" label="Quantity" value={recommendation.quantity} />
            <ReportCard icon="⏰" label="Best Timing" value={recommendation.timing} />
            <ReportCard icon="💧" label="Irrigation" value={recommendation.irrigationAdvice} />
          </div>

          {/* Detail Cards */}
          <div className="report-details-grid">
            <div className="detail-card glass-card">
              <div className="detail-card-head">
                <span className="detail-card-icon">🔬</span>
                <h4>Why This Fertilizer?</h4>
              </div>
              <p className="detail-card-body">{recommendation.reason || 'Analysis complete.'}</p>
            </div>
            <div className="detail-card glass-card">
              <div className="detail-card-head">
                <span className="detail-card-icon">📋</span>
                <h4>Application Method</h4>
              </div>
              <p className="detail-card-body">{recommendation.applicationMethod || 'Follow label instructions.'}</p>
            </div>
            <div className="detail-card glass-card">
              <div className="detail-card-head">
                <span className="detail-card-icon">⚠️</span>
                <h4>Precautions</h4>
              </div>
              <p className="detail-card-body">{recommendation.precautions || 'Handle with standard care.'}</p>
            </div>
            <div className="detail-card glass-card">
              <div className="detail-card-head">
                <span className="detail-card-icon">🌿</span>
                <h4>Organic Alternatives</h4>
              </div>
              <p className="detail-card-body">{recommendation.organicAlternatives || 'N/A'}</p>
            </div>
          </div>

          {/* Expected Improvement */}
          <div className="improvement-card glass-card">
            <div className="improvement-icon">📈</div>
            <div className="improvement-text">
              <h4>Expected Improvement</h4>
              <p>{recommendation.expectedImprovement || 'Positive yield improvement expected within weeks of proper application.'}</p>
            </div>
          </div>

          {/* Chat Follow-up System */}
          <div className="chat-section glass-card" style={{ marginTop: '30px', padding: '20px' }}>
            <h4>💬 Ask Follow-up Questions</h4>
            <div className="chat-history" style={{ maxHeight: '300px', overflowY: 'auto', marginBottom: '15px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {chatMessages.length === 0 ? (
                <p style={{ color: '#aaa', fontStyle: 'italic', textAlign: 'center' }}>No questions yet. Ask about alternatives, local shops, or safety!</p>
              ) : (
                chatMessages.map((msg, idx) => (
                  <div key={idx} style={{
                    alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
                    backgroundColor: msg.role === 'user' ? 'var(--primary-color)' : 'rgba(255, 255, 255, 0.1)',
                    color: msg.role === 'user' ? '#fff' : 'var(--text-color)',
                    padding: '10px 15px',
                    borderRadius: '12px',
                    maxWidth: '80%'
                  }}>
                    <strong>{msg.role === 'user' ? 'You' : 'Agent'}:</strong> {msg.content}
                  </div>
                ))
              )}
              {chatLoading && (
                <div style={{ alignSelf: 'flex-start', padding: '10px 15px', fontStyle: 'italic', opacity: 0.7 }}>
                  Agent is typing...
                </div>
              )}
            </div>
            <form onSubmit={handleChatSubmit} style={{ display: 'flex', gap: '10px' }}>
              <input 
                type="text" 
                value={chatInput} 
                onChange={(e) => setChatInput(e.target.value)} 
                placeholder="Type your question..." 
                style={{ flex: 1, padding: '12px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.2)', background: 'rgba(255,255,255,0.05)', color: '#fff' }} 
              />
              <button type="submit" className="btn-primary" disabled={chatLoading}>Send</button>
            </form>
          </div>

          {/* New Recommendation CTA */}
          <div className="new-rec-cta">
            <button className="btn-primary" onClick={handleReset}>
              + New Recommendation
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;
